replicaCount: 1
image:
  repository: c63eqfuv.c1.gra9.container-registry.ovh.net/gfts/webapp
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

ingress:
  enabled: false

ingress-nginx:
  controller:
    ingressClass: "nginx"
    replicaCount: 1
  fullnameOverride: "ingress-nginx"
  hosts:
    - host: gfts.developmentseed.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe:
  httpGet:
    path: /
    port: 9000
readinessProbe:
  httpGet:
    path: /
    port: 9000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
